// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_FHk9utoJ9MZdB0p6sJcEgZSCoe9wynM',
    appId: '1:296340636091:web:235f4c6fb5b7df463c449e',
    messagingSenderId: '296340636091',
    projectId: 'i-click-app-d0f07',
    authDomain: 'i-click-app-d0f07.firebaseapp.com',
    databaseURL: 'https://i-click-app-d0f07-default-rtdb.firebaseio.com',
    storageBucket: 'i-click-app-d0f07.appspot.com',
    measurementId: 'G-VNG6Z3BHX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlcbJA3Fyko6ByQ4SYHNWmmNSThyQ6yrU',
    appId: '1:296340636091:android:a196e5ebe17b0e153c449e',
    messagingSenderId: '296340636091',
    projectId: 'i-click-app-d0f07',
    databaseURL: 'https://i-click-app-d0f07-default-rtdb.firebaseio.com',
    storageBucket: 'i-click-app-d0f07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALTJv92W5BpoInZ22I3yDpl-d1j5knYaQ',
    appId: '1:296340636091:ios:c98c2879eb1be89e3c449e',
    messagingSenderId: '296340636091',
    projectId: 'i-click-app-d0f07',
    databaseURL: 'https://i-click-app-d0f07-default-rtdb.firebaseio.com',
    storageBucket: 'i-click-app-d0f07.appspot.com',
    iosBundleId: 'com.example.iClick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALTJv92W5BpoInZ22I3yDpl-d1j5knYaQ',
    appId: '1:296340636091:ios:b0957dbecd1ef3f23c449e',
    messagingSenderId: '296340636091',
    projectId: 'i-click-app-d0f07',
    databaseURL: 'https://i-click-app-d0f07-default-rtdb.firebaseio.com',
    storageBucket: 'i-click-app-d0f07.appspot.com',
    iosBundleId: 'com.example.iClick.RunnerTests',
  );
}
